#!/usr/bin/env python3
"""Generate a dependency-free line-hit coverage report using stdlib trace."""
import argparse
import json
import sys
import trace
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_FILES = [
    "image-studio.py",
    "do-anthropic-proxy.py",
    "matts-console.py",
    "src/console/handlers/auth_handler.py",
    "src/console/handlers/static_handler.py",
    "src/console/handlers/template_handler.py",
    "src/console/handlers/websocket_handler.py",
    "src/console/services/agentboard.py",
    "src/console/services/chat.py",
    "src/console/services/dedicated.py",
    "src/console/services/digitalocean.py",
    "src/console/services/health.py",
    "src/console/services/http_json.py",
    "src/console/services/image_generation.py",
    "src/console/services/model_registry.py",
    "src/console/services/persistence.py",
    "src/console/services/proxy_process.py",
    "src/console/services/runtime_config.py",
    "src/console/services/serverless_catalog.py",
    "src/console/services/session.py",
    "src/console/services/terminal.py",
    "src/console/services/tmux_control.py",
    "src/console/services/usage.py",
    "src/console/services/wallpaper.py",
    "src/console/services/websocket.py",
]


def measured_lines(path):
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    measured = set()
    in_multiline = False
    for index, raw in enumerate(lines, 1):
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        quote_count = stripped.count('"""') + stripped.count("'''")
        if in_multiline:
            if quote_count % 2:
                in_multiline = False
            continue
        if stripped.startswith(('"""', "'''")):
            if quote_count % 2:
                in_multiline = True
            continue
        measured.add(index)
    return measured


def run_tests_under_trace(test_dir):
    tracer = trace.Trace(
        count=True,
        trace=False,
        ignoredirs=[sys.prefix, sys.exec_prefix],
    )
    suite = unittest.defaultTestLoader.discover(str(test_dir))
    runner = unittest.TextTestRunner(verbosity=2)
    result = tracer.runfunc(runner.run, suite)
    return tracer.results(), result


def build_report(results, files):
    counts = results.counts
    rows = []
    for rel in files:
        path = (ROOT / rel).resolve()
        measured = measured_lines(path)
        executed = {
            lineno
            for (filename, lineno), count in counts.items()
            if Path(filename).resolve() == path and count > 0
        }
        covered = measured & executed
        missed = sorted(measured - executed)
        percent = (len(covered) / len(measured) * 100.0) if measured else 100.0
        rows.append({
            "file": rel,
            "measured_lines": len(measured),
            "covered_lines": len(covered),
            "missed_lines": missed,
            "coverage_percent": round(percent, 2),
        })
    total_measured = sum(row["measured_lines"] for row in rows)
    total_covered = sum(row["covered_lines"] for row in rows)
    total_percent = (total_covered / total_measured * 100.0) if total_measured else 100.0
    return {
        "summary": {
            "files": len(rows),
            "measured_lines": total_measured,
            "covered_lines": total_covered,
            "coverage_percent": round(total_percent, 2),
        },
        "files": rows,
    }


def write_markdown(report, path):
    lines = [
        "# Coverage Report",
        "",
        "| File | Covered | Measured | Percent |",
        "| --- | ---: | ---: | ---: |",
    ]
    for row in report["files"]:
        lines.append("| {file} | {covered_lines} | {measured_lines} | {coverage_percent:.2f}% |".format(**row))
    summary = report["summary"]
    lines.extend([
        "| **Total** | {covered_lines} | {measured_lines} | {coverage_percent:.2f}% |".format(**summary),
        "",
        "Generated by `scripts/coverage-report.py` using Python `trace`.",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default="build/coverage", help="directory for coverage artifacts")
    parser.add_argument("--fail-under", type=float, default=0.0, help="fail when total percent is below this value")
    parser.add_argument("--file", action="append", dest="files", help="tracked file to include; can be repeated")
    args = parser.parse_args()

    files = args.files or DEFAULT_FILES
    output_dir = ROOT / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    results, test_result = run_tests_under_trace(ROOT / "tests")
    report = build_report(results, files)
    (output_dir / "coverage.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(report, output_dir / "coverage.md")

    summary = report["summary"]
    print("Coverage: {coverage_percent:.2f}% ({covered_lines}/{measured_lines} lines)".format(**summary))
    print("Coverage artifacts: %s" % output_dir)
    if not test_result.wasSuccessful():
        return 1
    if summary["coverage_percent"] < args.fail_under:
        print("Coverage is below required threshold %.2f%%" % args.fail_under, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
