#!/usr/bin/env python3
"""Generate the v2 OpenAPI document and lightweight TypeScript client."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OPENAPI_PATH = ROOT / "frontend" / "src" / "api" / "generated" / "openapi.json"
CLIENT_PATH = ROOT / "frontend" / "src" / "api" / "generated" / "v2Client.ts"


CLIENT_SOURCE = """// Generated by scripts/generate-v2-openapi.py. Do not edit by hand.
import { consoleAuthHeaders, withConsoleToken } from '../auth';
import { responseJsonOrThrow } from '../errors';
import type { CapabilitiesPayload } from '../capabilities';
import type { TuiStatus } from '../tui';

async function requestJson<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(withConsoleToken(path), {
    ...init,
    headers: {
      'content-type': 'application/json',
      ...consoleAuthHeaders(),
      ...(init?.headers || {})
    }
  });
  return responseJsonOrThrow<T>(response);
}

export type ActorIdentity = {
  id: string;
  roles: string[];
  permissions: string[];
  source: string;
  session_id?: string;
};

export type PolicyDecision = {
  action: string;
  allowed: boolean;
  required_permission: string;
  reason: string;
  actor_id: string;
  details: Record<string, unknown>;
};

export type PromptTemplate = {
  id: string;
  name: string;
  description: string;
  body: string;
  variables: string[];
  examples: Array<{ title: string; values: string; rendered: string; note: string }>;
  owner_notes: string;
  tags: string[];
  version: number;
  created_at: number;
  updated_at: number;
  eval_gate?: EvalGateRecord;
};

export type PromptTemplateVersion = PromptTemplate & {
  template_id: string;
  archived_at: number;
};

export type PromptTemplatePreview = {
  body: string;
  rendered: string;
  variables: string[];
  used_variables: string[];
  missing_variables: string[];
};

export type RunProfile = {
  id: string;
  name: string;
  description: string;
  model: string;
  template_id: string;
  settings: Record<string, unknown>;
  tags: string[];
  version: number;
  active: boolean;
  created_at: number;
  updated_at: number;
  eval_gate?: EvalGateRecord;
};

export type RunProfileVersion = RunProfile & {
  profile_id: string;
  archived_at: number;
};

export type ConversationBranch = {
  id: string;
  title: string;
  root_session_id: string;
  parent_branch_id: string;
  summary: string;
  messages: Array<Record<string, unknown>>;
  metadata: Record<string, unknown>;
  tags: string[];
  version: number;
  created_at: number;
  updated_at: number;
};

export type SessionSnapshot = {
  id: string;
  session_id: string;
  title: string;
  trace_id: string;
  summary: string;
  agentboard: Record<string, unknown>;
  resource: Record<string, unknown>;
  tags: string[];
  version: number;
  created_at: number;
  updated_at: number;
};

export type RunRecord = {
  id: string;
  title: string;
  trace_id: string;
  session_id: string;
  profile_id: string;
  profile_version: number;
  prompt_template_id: string;
  prompt_template_version: number;
  status: string;
  input: Record<string, unknown>;
  result: Record<string, unknown>;
  metadata: Record<string, unknown>;
  tags: string[];
  created_at: number;
  updated_at: number;
};

export type EvalGate = {
  surface: string;
  decision: string;
  allowed: boolean;
  would_allow: boolean;
  required: boolean;
  status: string;
  change: Record<string, unknown>;
  recommended_datasets: Array<Record<string, unknown>>;
  evidence: Array<Record<string, unknown>>;
  policy: Record<string, unknown>;
  override: Record<string, unknown>;
  created_at: number;
  target_id?: string;
  target_version?: number;
};

export type EvalGateRecord = {
  id: string;
  surface: string;
  target_id: string;
  target_version: number;
  decision: string;
  allowed: boolean;
  required: boolean;
  change_hash: string;
  gate: EvalGate;
  created_at: number;
};

export type RunWorkspacePayload = {
  prompt_templates: PromptTemplate[];
  run_profiles: RunProfile[];
  active_run_profile: RunProfile | null;
  run_records: RunRecord[];
  eval_gate_records: EvalGateRecord[];
  conversation_branches: ConversationBranch[];
  session_snapshots: SessionSnapshot[];
  local_rag: LocalRagPayload;
  database: string;
};

export type OnboardingModelTemplatesPayload = {
  generator: string;
  summary: {
    target: number;
    existing: number;
    missing: number;
    seeded: number;
  };
  items: Array<{
    model: Record<string, unknown>;
    template: PromptTemplate;
    status: string;
    preview: {
      rendered: string;
      variables: string[];
    };
  }>;
};

export type OnboardingPayload = {
  onboarding: Record<string, unknown>;
  model_templates: OnboardingModelTemplatesPayload;
};

export type LocalRagCollection = {
  id: string;
  name: string;
  include: string[];
  exclude: string[];
  max_file_bytes: number;
};

export type LocalRagPayload = {
  config: {
    schema_version: number;
    collections: LocalRagCollection[];
  };
  index: Array<Record<string, unknown>>;
  runtime_excludes: string[];
};

export type LocalRagSearchResult = {
  query: string;
  collection_id: string;
  matches: Array<Record<string, unknown>>;
  collections: string[];
};

export type ReplaySnapshot = {
  source: Record<string, unknown>;
  model: string;
  messages: Array<Record<string, unknown>>;
  available: boolean;
  redaction: string;
  limitations: string[];
  original?: Record<string, unknown>;
};

export type ReplayRecord = {
  id: string;
  created_at: number;
  source: Record<string, unknown>;
  snapshot: Record<string, unknown>;
  targets: string[];
  results: Array<Record<string, unknown>>;
  summary: Record<string, unknown>;
};

export type WorkspaceBundleSummary = {
  id: string;
  path: string;
  created_at: number;
  sections: string[];
  redaction: Record<string, unknown>;
  valid: boolean;
};

export type WorkspaceBundleExport = {
  bundle: Record<string, unknown>;
  bundle_id: string;
  path: string;
  summary: Record<string, unknown>;
};

export type WorkspaceBundlePreview = {
  manifest: Record<string, unknown>;
  selected_sections: string[];
  summary: Record<string, unknown>;
  issues: Array<Record<string, unknown>>;
  blocking: boolean;
  dry_run: boolean;
  applied?: string[];
};

export type ContextWindowPayload = {
  action: string;
  generated_at: number;
  approximate: boolean;
  input_tokens_est: number;
  message_count: number;
  messages: Array<Record<string, unknown>>;
  models: Array<Record<string, unknown>>;
  warnings: Array<Record<string, unknown>>;
  assumptions: string[];
};

export type ChatRunPayload = {
  model?: string;
  messages: Array<Record<string, unknown>>;
  max_tokens?: number;
  temperature?: number | string;
  run_profile_id?: string;
  prompt_template_id?: string;
};

export type ObservePayload = {
  console: Record<string, unknown>;
  cost: Record<string, unknown>;
  analytics: Record<string, unknown>;
  provider_health: Record<string, unknown>;
  traces: Array<Record<string, unknown>>;
  audit: Record<string, unknown>;
  evals: EvalPayload;
  telemetry: TelemetryPayload;
  reporting_export: Record<string, unknown>;
  reporting_integrations: Record<string, unknown>;
};

export type EvalPayload = {
  datasets: Array<Record<string, unknown>>;
  runs: Array<Record<string, unknown>>;
  summary: Record<string, unknown>;
  error?: string;
};

export type ReportingExportResult = {
  export_id?: string;
  schema_version?: number;
  format: string;
  path: string;
  tables?: Record<string, number>;
  redaction_mode?: string;
  exported_at?: number;
  source_fingerprints?: Record<string, unknown>;
  warnings?: string[];
};

export type TelemetryPayload = {
  metrics: Record<string, unknown>;
  exporter: Record<string, unknown>;
  privacy: Record<string, unknown>;
  metric_families: string[];
  label_keys: string[];
  policy: Record<string, unknown>;
};

export type OperatePayload = {
  generated_at: number;
  eval_gates: Record<string, unknown>;
  reviews: Record<string, unknown>;
  release_candidate: Record<string, unknown>;
  rollback: Record<string, unknown>;
  config_drift: Record<string, unknown>;
  automation: Record<string, unknown>;
  quotas: Record<string, unknown>;
  synthetic_load: Record<string, unknown>;
  ci_triage: Record<string, unknown>;
  offline_mode: Record<string, unknown>;
  model_deprecations: Record<string, unknown>;
  summary: Record<string, unknown>;
};

export type DecisionExplanation = {
  id: string;
  type: string;
  title: string;
  deterministic: boolean;
  confidence: string;
  selected_action: string;
  reason: string;
  inputs: Record<string, unknown>;
  matched_policy: Record<string, unknown>;
  candidates: Array<unknown>;
  rejected_alternatives: Array<unknown>;
  evidence_links: Array<Record<string, unknown>>;
  raw: Record<string, unknown>;
  generated_at: number;
  privacy: string;
};

export type ConsoleOverviewPayload = {
  generated_at: number;
  sessions: Array<Record<string, unknown>>;
  agentboard: Record<string, unknown>;
  counts: Record<string, number>;
  tasks: Array<Record<string, unknown>>;
  leaderboard: Array<Record<string, unknown>>;
  usage: Record<string, unknown>;
  evals: Record<string, unknown>;
  summary: {
    sessions_total: number;
    sessions_live: number;
    agent_sessions: number;
    requests_ok: number;
    requests_error: number;
    spend_usd: number;
  };
  errors: Record<string, string>;
};

export type TmuxWorkspacePayload = {
  generated_at: number;
  sessions: Array<Record<string, unknown>>;
  previous_sessions?: Array<Record<string, unknown>>;
  allowed_keys: string[];
  terminal: {
    path: string;
    query_param: string;
    websocket_path: string;
    default_legacy_port: number;
  };
  summary: {
    sessions_total: number;
    sessions_live: number;
    sessions_read_only: number;
    sessions_previous?: number;
    sessions_attached: number;
    estimated_cost_usd: number;
    estimated_tokens: number;
  };
  errors: Record<string, string>;
};

export type ConsoleCommand = {
  id: string;
  title: string;
  group: string;
  permission: string;
  action: Record<string, unknown>;
  contextual?: boolean;
  keywords?: string[];
  context_ready: boolean;
  available: boolean;
};

export type ConsoleCommandsPayload = {
  generated_at: number;
  commands: ConsoleCommand[];
  summary: Record<string, number>;
  shortcut?: string;
};

export type CodeSessionDefaultsPayload = {
  default_name: string;
  default_project_dir: string;
  default_model: string;
  text_models: string[];
  profiles: Array<Record<string, unknown>>;
};

export type CodeSessionStartPayload = {
  name?: string;
  display_name?: string;
  new_session?: boolean;
  model?: string;
  project_dir?: string;
  permission_mode?: string;
  run_mode?: string;
  print_prompt?: string;
  profile?: string;
  cols?: number;
  rows?: number;
};

export type PermissionPreview = {
  mode: string;
  risk_level: string;
  allows_edits: boolean;
  allows_bash: boolean;
  categories: Record<string, unknown>;
  paths: Array<Record<string, unknown>>;
  warnings: Array<Record<string, unknown>>;
  suggested_preset: Record<string, unknown>;
  override_allowed: boolean;
};

export function getHealth(): Promise<{ status: string; version: string }> {
  return requestJson('/v2/health');
}

export function getMe(): Promise<{ actor: ActorIdentity }> {
  return requestJson('/v2/me');
}

export function getMeCapabilities(): Promise<CapabilitiesPayload> {
  return requestJson('/v2/me/capabilities');
}

export function decidePolicy(action: string): Promise<{ decision: PolicyDecision }> {
  return requestJson('/v2/policy/decide', {
    method: 'POST',
    body: JSON.stringify({ action })
  });
}

export function getRunWorkspace(): Promise<RunWorkspacePayload> {
  return requestJson('/v2/run');
}

export function getOnboarding(): Promise<OnboardingPayload> {
  return requestJson('/v2/onboarding');
}

export function seedOnboardingModelTemplates(): Promise<OnboardingPayload> {
  return requestJson('/v2/onboarding/model-templates/seed', {
    method: 'POST',
    body: JSON.stringify({})
  });
}

export function completeOnboardingItem(payload: { id: string; note?: string } & Record<string, unknown>): Promise<OnboardingPayload> {
  return requestJson('/v2/onboarding/complete', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getLocalRag(): Promise<{ local_rag: LocalRagPayload }> {
  return requestJson('/v2/run/rag');
}

export function saveLocalRagConfig(payload: { collections: LocalRagCollection[] }): Promise<{ config: LocalRagPayload['config'] }> {
  return requestJson('/v2/run/rag/config', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function indexLocalRag(collectionId = ''): Promise<{ index: Record<string, unknown> }> {
  return requestJson('/v2/run/rag/index', {
    method: 'POST',
    body: JSON.stringify(collectionId ? { collection_id: collectionId } : {})
  });
}

export function searchLocalRag(payload: { query: string; collection_id?: string; limit?: number }): Promise<{ results: LocalRagSearchResult }> {
  return requestJson('/v2/run/rag/search', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function listReplays(limit = 50): Promise<{ replays: ReplayRecord[] }> {
  return requestJson(`/v2/run/replays?limit=${encodeURIComponent(String(limit))}`);
}

export function snapshotReplay(payload: { source: { type: string; id?: string; chat_id?: string; trace_id?: string; message_index?: number | string } }): Promise<{ snapshot: ReplaySnapshot }> {
  return requestJson('/v2/run/replay/snapshot', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function runReplay(payload: { source?: Record<string, unknown>; snapshot?: ReplaySnapshot; target?: string; models?: string[]; baseline_text?: string; max_tokens?: number; temperature?: number | string }): Promise<ReplayRecord> {
  return requestJson('/v2/run/replay', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function listWorkspaceBundles(): Promise<{ bundles: WorkspaceBundleSummary[] }> {
  return requestJson('/v2/run/workspace-bundles');
}

export function exportWorkspaceBundle(payload: { sections?: string[]; id?: string }): Promise<WorkspaceBundleExport> {
  return requestJson('/v2/run/workspace-bundles/export', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewWorkspaceBundleImport(payload: Record<string, unknown>): Promise<WorkspaceBundlePreview> {
  return requestJson('/v2/run/workspace-bundles/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function importWorkspaceBundle(payload: Record<string, unknown>): Promise<WorkspaceBundlePreview> {
  return requestJson('/v2/run/workspace-bundles/import', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function inspectContextWindow(payload: { action?: string; payload?: Record<string, unknown> } & Record<string, unknown>): Promise<ContextWindowPayload> {
  return requestJson('/v2/run/context-window', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function runChat(payload: ChatRunPayload): Promise<{ status: number; response: Record<string, unknown> }> {
  return requestJson('/v2/run/chat', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export type ResearchDossier = Record<string, unknown>;
export type ResearchReportPacket = Record<string, unknown>;

export function getResearchCatalog(): Promise<Record<string, unknown>> {
  return requestJson('/v2/research');
}

export function runResearchSearch(payload: Record<string, unknown>): Promise<ResearchDossier> {
  return requestJson('/v2/research/search', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getResearchDossier(dossierId: string): Promise<ResearchDossier> {
  return requestJson(`/v2/research/dossiers/${encodeURIComponent(dossierId)}`);
}

export function updateResearchPins(dossierId: string, evidenceIds: string[]): Promise<ResearchDossier> {
  return requestJson(`/v2/research/dossiers/${encodeURIComponent(dossierId)}/pins`, {
    method: 'PATCH',
    body: JSON.stringify({ evidence_ids: evidenceIds })
  });
}

export function getResearchReport(dossierId: string): Promise<ResearchReportPacket> {
  return requestJson(`/v2/research/dossiers/${encodeURIComponent(dossierId)}/report`);
}

export function getObserve(days = 7, traceLimit = 50, auditLimit = 50): Promise<ObservePayload> {
  const params = new URLSearchParams({
    days: String(days),
    trace_limit: String(traceLimit),
    audit_limit: String(auditLimit)
  });
  return requestJson(`/v2/observe?${params.toString()}`);
}

export function getObserveTraces(filters: { limit?: number; model?: string; status?: string; session?: string } = {}): Promise<{ traces: Array<Record<string, unknown>> }> {
  const params = new URLSearchParams();
  params.set('limit', String(filters.limit || 100));
  if (filters.model) params.set('model', filters.model);
  if (filters.status) params.set('status', filters.status);
  if (filters.session) params.set('session', filters.session);
  return requestJson(`/v2/observe/traces?${params.toString()}`);
}

export function searchObserveAudit(payload: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
  return requestJson('/v2/observe/audit', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getObserveEvals(): Promise<EvalPayload> {
  return requestJson('/v2/observe/evals');
}

export function getObserveTelemetry(): Promise<TelemetryPayload> {
  return requestJson('/v2/observe/telemetry');
}

export function exportObserveReporting(payload: { format?: string } = { format: 'duckdb' }): Promise<ReportingExportResult> {
  return requestJson('/v2/observe/reporting-export', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function explainObserveDecision(payload: { trace_id?: string; type?: string; record?: Record<string, unknown> }): Promise<DecisionExplanation> {
  return requestJson('/v2/observe/decisions/explain', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getOperate(): Promise<OperatePayload> {
  return requestJson('/v2/operate');
}

export function previewOperateCiTriage(payload: { reference?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/ci-triage/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function launchOperateCiTriage(payload: { reference?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/ci-triage/launch', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewOperateRepositoryContext(payload: { reference?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/repository-context/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function importOperateRepositoryContext(payload: { reference?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/repository-context/import', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function writeOperateReleaseReport(payload: { label?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/release/report', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function markOperateConfigDriftBaseline(payload: { label?: string; reason?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/config-drift/baseline', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function acknowledgeOperateConfigDrift(payload: { items?: string[]; reason?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/config-drift/acknowledge', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewOperateRollback(payload: { target_id?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/rollback/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function applyOperateRollback(payload: { target_id?: string; reason?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/rollback/apply', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function updateOperateReview(payload: { id?: string; review_id?: string; status?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/reviews/update', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function promoteOperateReview(payload: { id?: string; review_id?: string; target?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/reviews/promote', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function saveOperateEvalDataset(payload: Record<string, unknown>): Promise<{ dataset: Record<string, unknown> }> {
  return requestJson('/v2/operate/evals/datasets', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function buildOperateEvalDataset(payload: Record<string, unknown>): Promise<{ dataset: Record<string, unknown> }> {
  return requestJson('/v2/operate/evals/datasets/build', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function runOperateEval(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/evals/run', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function saveOperateAutomationRules(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/automation/rules', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function testOperateAutomation(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/automation/test', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function runOperateAutomation(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/automation/run', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function runDueOperateAutomationSchedules(payload: { dry_run?: boolean } & Record<string, unknown> = {}): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/automation/schedules/run-due', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewOperateModelDeprecation(payload: { model_id?: string; model?: string; replacement_model?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/model-deprecations/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function applyOperateModelDeprecation(payload: { model_id?: string; model?: string; replacement_model?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/model-deprecations/apply', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function rollbackOperateModelDeprecation(payload: { migration_id?: string; id?: string } & Record<string, unknown>): Promise<Record<string, unknown>> {
  return requestJson('/v2/operate/model-deprecations/rollback', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getConsoleOverview(): Promise<ConsoleOverviewPayload> {
  return requestJson('/v2/console/overview');
}

export function getConsoleCommands(query = '', context: { session?: string; trace_id?: string; model?: string } = {}): Promise<ConsoleCommandsPayload> {
  const params = new URLSearchParams();
  if (query) params.set('q', query);
  if (context.session) params.set('session', context.session);
  if (context.trace_id) params.set('trace_id', context.trace_id);
  if (context.model) params.set('model', context.model);
  const suffix = params.toString() ? `?${params.toString()}` : '';
  return requestJson(`/v2/console/commands${suffix}`);
}

export function dispatchConsoleCommand(id: string, context: Record<string, unknown> = {}): Promise<{ command: ConsoleCommand; action: Record<string, unknown>; dispatched_at: number }> {
  return requestJson('/v2/console/commands/dispatch', {
    method: 'POST',
    body: JSON.stringify({ id, context })
  });
}

export function getCodeSessionDefaults(): Promise<CodeSessionDefaultsPayload> {
  return requestJson('/v2/console/code-sessions/defaults');
}

export function listCodeSessions(): Promise<{ sessions: Array<Record<string, unknown>> }> {
  return requestJson('/v2/console/code-sessions');
}

export function getTmuxWorkspace(): Promise<TmuxWorkspacePayload> {
  return requestJson('/v2/console/tmux');
}

export function startTmuxSession(payload: CodeSessionStartPayload): Promise<Record<string, unknown>> {
  return requestJson('/v2/console/tmux/start', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function captureTmuxSession(name: string): Promise<{ name: string; screen: string }> {
  return requestJson('/v2/console/tmux/capture', {
    method: 'POST',
    body: JSON.stringify({ name })
  });
}

export function sendTmuxText(name: string, text: string, enter = true): Promise<{ ok: boolean }> {
  return requestJson('/v2/console/tmux/send', {
    method: 'POST',
    body: JSON.stringify({ name, text, enter })
  });
}

export function sendTmuxKey(name: string, key: string): Promise<{ ok: boolean }> {
  return requestJson('/v2/console/tmux/key', {
    method: 'POST',
    body: JSON.stringify({ name, key })
  });
}

export function renameTmuxSession(oldName: string, newName: string, displayName = ''): Promise<Record<string, unknown>> {
  return requestJson('/v2/console/tmux/rename', {
    method: 'POST',
    body: JSON.stringify({ old_name: oldName, new_name: newName, display_name: displayName })
  });
}

export function stopTmuxSession(name: string): Promise<{ ok: boolean }> {
  return requestJson('/v2/console/tmux/stop', {
    method: 'POST',
    body: JSON.stringify({ name })
  });
}

export function startCodeSession(payload: CodeSessionStartPayload): Promise<Record<string, unknown>> {
  return requestJson('/v2/console/code-sessions/start', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewCodeSessionPermissions(payload: CodeSessionStartPayload): Promise<{ permission_preview: PermissionPreview }> {
  return requestJson('/v2/console/code-sessions/permissions', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function captureCodeSession(name: string): Promise<{ name: string; screen: string }> {
  return requestJson('/v2/console/code-sessions/capture', {
    method: 'POST',
    body: JSON.stringify({ name })
  });
}

export function sendCodeSessionInput(name: string, text: string, enter = true): Promise<{ ok: boolean }> {
  return requestJson('/v2/console/code-sessions/send', {
    method: 'POST',
    body: JSON.stringify({ name, text, enter })
  });
}

export function stopCodeSession(name: string): Promise<{ ok: boolean }> {
  return requestJson('/v2/console/code-sessions/stop', {
    method: 'POST',
    body: JSON.stringify({ name })
  });
}

export function savePromptTemplate(payload: Partial<PromptTemplate> & { eval_gate?: Record<string, unknown> }): Promise<{ prompt_template: PromptTemplate }> {
  return requestJson('/v2/run/prompt-templates', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function previewPromptTemplate(payload: { template_id?: string; body?: string; variables?: string[]; values?: Record<string, unknown> }): Promise<{ preview: PromptTemplatePreview }> {
  return requestJson('/v2/run/prompt-templates/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function listPromptTemplateVersions(templateId: string): Promise<{ versions: PromptTemplateVersion[] }> {
  return requestJson(`/v2/run/prompt-templates/${encodeURIComponent(templateId)}/versions`);
}

export function rollbackPromptTemplate(templateId: string, version: number): Promise<{ prompt_template: PromptTemplate }> {
  return requestJson(`/v2/run/prompt-templates/${encodeURIComponent(templateId)}/rollback`, {
    method: 'POST',
    body: JSON.stringify({ version })
  });
}

export function saveRunProfile(payload: Partial<RunProfile> & { eval_gate?: Record<string, unknown> }): Promise<{ run_profile: RunProfile }> {
  return requestJson('/v2/run/profiles', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function listRunProfileVersions(profileId: string): Promise<{ versions: RunProfileVersion[] }> {
  return requestJson(`/v2/run/profiles/${encodeURIComponent(profileId)}/versions`);
}

export function previewEvalGate(payload: { surface: string; before?: Record<string, unknown>; after?: Record<string, unknown>; policy?: Record<string, unknown>; eval_gate?: Record<string, unknown> }): Promise<{ eval_gate: EvalGate }> {
  return requestJson('/v2/run/eval-gates/preview', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function listEvalGateRecords(targetId = ''): Promise<{ eval_gate_records: EvalGateRecord[] }> {
  const suffix = targetId ? `?target_id=${encodeURIComponent(targetId)}` : '';
  return requestJson(`/v2/run/eval-gates${suffix}`);
}

export function activateRunProfile(profileId: string, evalGate?: Record<string, unknown>): Promise<{ run_profile: RunProfile }> {
  return requestJson(`/v2/run/profiles/${encodeURIComponent(profileId)}/activate`, {
    method: 'POST',
    body: JSON.stringify(evalGate ? { eval_gate: evalGate } : {})
  });
}

export function rollbackRunProfile(profileId: string, version: number): Promise<{ run_profile: RunProfile }> {
  return requestJson(`/v2/run/profiles/${encodeURIComponent(profileId)}/rollback`, {
    method: 'POST',
    body: JSON.stringify({ version })
  });
}

export function saveRunRecord(payload: Partial<RunRecord>): Promise<{ run_record: RunRecord }> {
  return requestJson('/v2/run/records', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function saveConversationBranch(payload: Partial<ConversationBranch>): Promise<{ conversation_branch: ConversationBranch }> {
  return requestJson('/v2/run/branches', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function saveSessionSnapshot(payload: Partial<SessionSnapshot>): Promise<{ session_snapshot: SessionSnapshot }> {
  return requestJson('/v2/run/session-snapshots', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}

export function getConsoleTuiStatus(): Promise<TuiStatus> {
  return requestJson('/v2/console/tui/status');
}

export function acquireConsoleTuiControl(clientId: string, force = false): Promise<{ lease: TuiStatus['lease'] }> {
  return requestJson('/v2/console/tui/control/acquire', {
    method: 'POST',
    body: JSON.stringify({ client_id: clientId, force })
  });
}

export function releaseConsoleTuiControl(clientId: string, force = false): Promise<{ lease: TuiStatus['lease'] }> {
  return requestJson('/v2/console/tui/control/release', {
    method: 'POST',
    body: JSON.stringify({ client_id: clientId, force })
  });
}

export function restartConsoleTui(): Promise<TuiStatus> {
  return requestJson('/v2/console/tui/restart', { method: 'POST', body: JSON.stringify({}) });
}
"""


def load_app():
    try:
        from backend.v2.app import app
    except Exception as exc:
        raise SystemExit("Unable to import v2 FastAPI app. Install requirements-v2.txt first. %s" % exc)
    if app is None:
        raise SystemExit("FastAPI app is unavailable. Install requirements-v2.txt first.")
    return app


def rendered_openapi(app):
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def generated_artifacts(app):
    return {
        "openapi": rendered_openapi(app),
        "client": CLIENT_SOURCE,
    }


def write_artifacts(artifacts, openapi_path=OPENAPI_PATH, client_path=CLIENT_PATH):
    openapi_path = Path(openapi_path)
    client_path = Path(client_path)
    openapi_path.parent.mkdir(parents=True, exist_ok=True)
    client_path.parent.mkdir(parents=True, exist_ok=True)
    openapi_path.write_text(artifacts["openapi"], encoding="utf-8")
    client_path.write_text(artifacts["client"], encoding="utf-8")
    print("wrote %s" % openapi_path)
    print("wrote %s" % client_path)


def drift_messages(artifacts, openapi_path=OPENAPI_PATH, client_path=CLIENT_PATH):
    openapi_path = Path(openapi_path)
    client_path = Path(client_path)
    checks = [
        ("OpenAPI document", openapi_path, artifacts["openapi"]),
        ("TypeScript client", client_path, artifacts["client"]),
    ]
    messages = []
    for label, path, expected in checks:
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as exc:
            messages.append("%s is missing or unreadable at %s: %s" % (label, path, exc))
            continue
        if actual != expected:
            messages.append("%s is stale at %s; run python3 scripts/generate-v2-openapi.py" % (label, path))
    return messages


def check_artifacts(artifacts, openapi_path=OPENAPI_PATH, client_path=CLIENT_PATH):
    messages = drift_messages(artifacts, openapi_path=openapi_path, client_path=client_path)
    if messages:
        for message in messages:
            print(message, file=sys.stderr)
        return 1
    print("V2 OpenAPI and generated client are current.")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate generated artifacts without rewriting files")
    args = parser.parse_args(argv)
    app = load_app()
    artifacts = generated_artifacts(app)
    if args.check:
        return check_artifacts(artifacts)
    write_artifacts(artifacts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
